### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by algebravic** [disteph/yicesQS#1]
I did a `git clone` of the repository and executed the first two lines of README to get the dependencies.  However, when I type make I get the following

```
make
dune build
File "src/QF_API.ml", line 44, characters 48-66:
44 |         | Term App(f, [arg]) when Term.equal f (Model.epsilon_real()) ->
                                                     ^^^^^^^^^^^^^^^^^^
Error: Unbound value Model.epsilon_real
File "src/solver.ml", line 232, characters 12-16:
232 |           | _::_ ->
                  ^^^^
Warning 11 [redundant-case]: this match case is unused.
File "src/IC.ml", line 924, characters 6-12:   
924 |   let (let*) = bind
            ^^^^^^
Warning 32 [unused-value-declaration]: unused value let*.
File "src/IC.ml", line 925, characters 6-12:
925 |   let (let+) a f = bind a (fun r -> return(f r))
            ^^^^^^
Warning 32 [unused-value-declaration]: unused value let+.
make: *** [build] Error 1                      
```

I'm using opam version 2.1.5 and ocaml version 5.0.0

**Comment by disteph** [comment]
Apologies, you need the yices-2.6.4-libpoly branch of the ocaml bindings for yices.

Try
opam pin yices2_bindings https://github.com/SRI-CSL/yices2_ocaml_bindings/archive/refs/heads/yices-2.6.4-libpoly.zip
instead of 
opam pin yices2_bindings https://github.com/SRI-CSL/yices2_ocaml_bindings/archive/refs/heads/yices-2.6.4.zip

That in turns requires to have Yices/MCSAT installed, with the libpoly and CUDD dependencies. That depends on how you installed Yices on your system. If you build Yices from source you need to configure Yices with --enable-mcsat.

**Comment by algebravic** [comment]
I had previously done `brew install yices2` but I had also done `opam install yices2` but that gives version 0.0.3!  I then went to the yices github, did a git clone, and did a configure with --enable-mcsat, but now when I do the `opam pin` above, it complains that it can't find libpoly_bindings.  I do have libpoly installed via homebrew and had to update the LIBRARY_PATH and C_INCLUDE_PATH to point to that and cudd,

**Comment by disteph** [comment]
If you have libpoly installed and Yices 2.6.4 installed with --enable-mcsat, then you're just missing the OCaml libpoly bindings
`opam pin libpoly_bindings https://github.com/SRI-CSL/libpoly_ocaml_bindings/archive/refs/heads/main.zip`
If it doesn't work for you, let's have an interactive session.
A better build system is work in progress.

**Comment by disteph** [comment]
I have updated the instructions.
